### ISSUE TITLE
Love this idea already

### ISSUE THREAD

**Issue by mxstbr** [henrythemes/jekyll-gutenberg-theme#1]

**Comment by geraldb** [comment]
@mxstbr  Thanks for your tweet - found Gutenberg that way. Will convert the Dr. Jekyll and Mr. Hyde book (see [/jekyll-book-theme](https://github.com/henrythemes/jekyll-book-theme)) using Gutenberg in the next days (if it works out). Jekyll (and GitHub Pages) has built-in support for Sass.

**Comment by geraldb** [comment]
@mxstbr  First version working / live. Cheers.
